#!/bin/sh
RAW_REQUEST="$(cat)"
echo "${RAW_REQUEST}" > ./request.txt
METHOD="$(echo "${RAW_REQUEST}" | grep -i '^Method:' | awk '{print $2}')"
NETWORK="$(echo "${RAW_REQUEST}" | grep -i '^Cred.Network:' | awk '{print $2}')"
TOKEN="$(echo "${RAW_REQUEST}" | grep -i '^Cred.Token:' | awk '{print $2}')"
echo "" > .out
RESPONSE=$(curl -s -o ./.out -w "%{http_code}" -X POST \
  -d "{\"cred\": \"${TOKEN}\"}" -H 'Content-Type: application/json' \
  "https://${NETWORK}/protocols/current_user_info")
if [ "$RESPONSE" -ne 200 ]; then
  echo "bash 500"
  echo "Content-Type: text/html;charset=UTF-8"
else
  echo "bash 200"
  echo "Content-Type: text/html;charset=UTF-8"
  echo
  echo "Method is ${METHOD:-} and your name is $(jq -r '.name' .out) $(jq -r '.surname' .out)"
fi
rm .out
exit 0
